import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import ClauseList from "../../components/attorney/ClauseList.js";
import ClauseDetailPanel from "../../components/attorney/ClauseDetailPanel.js";
import { useAuth } from "../../context/AuthContext.js";
import { getContractById } from "../../services/contractService.js";
import {
  completeContractReview,
  getContractFlags,
  type BackendFlag,
} from "../../services/attorneyService.js";
import type { ContractClause } from "../../types/clause.js";

function formatCategoryTitle(
  category: string | undefined,
  index: number,
  text: string,
): string {
  const titleMap: Record<string, string> = {
    wage_and_hours: "Wage & Working Hours",
    termination: "Termination & Due Process",
    non_compete: "Non-Compete Covenant",
    confidentiality: "Confidentiality Scope",
    liability_waiver: "Liability & Injury Waiver",
    intellectual_property: "IP Assignment",
    jurisdiction: "Jurisdiction & Venue",
    contracting_and_subcontracting: "Contracting Terms",
  };

  if (category && titleMap[category]) {
    return titleMap[category];
  }

  const firstLine = text.split("\n")[0]?.trim();
  if (firstLine && firstLine.length < 45 && !firstLine.includes('"')) {
    return firstLine;
  }

  return `Clause Section ${index + 1}`;
}

function transformFlagToClause(
  flag: BackendFlag,
  index: number,
): ContractClause {
  const primaryCategory = flag.riskCategories?.[0] || "other";
  const title = formatCategoryTitle(primaryCategory, index, flag.clauseText);

  const effectiveRisk = flag.attorneyRiskOverride || flag.aiRiskLevel || "low";
  const primaryStatute = flag.statutoryBases?.[0];

  const clause: ContractClause = {
    id: flag._id,
    clauseNumber: String(index + 1),
    title,
    riskLevel: effectiveRisk,
    originalAiRiskLevel: flag.aiRiskLevel || "low",
    attorneyStatus: flag.attorneyStatus || "pending",
    attorneyNote: flag.attorneyNote || "",
    quotedText: flag.clauseText,
  };

  if (flag.aiRationale) {
    clause.flagReason = flag.aiRationale;
  }

  if (primaryStatute) {
    clause.legalBasis = {
      citation: primaryStatute.citation,
      explanation: primaryStatute.excerpt,
    };
  }

  return clause;
}

/**
 * The live clause-by-clause AI-flagged review interface for attorneys.
 * Fetches real contract flags from MongoDB Atlas generated by the RAG pipeline.
 */
function ReviewQueuePage() {
  const navigate = useNavigate();
  const { contractId } = useParams<{ contractId: string }>();
  const { token } = useAuth();

  const [contractTitle, setContractTitle] = useState("Contract Review");
  const [contractType, setContractType] = useState("Employment Agreement");
  const [clauses, setClauses] = useState<ContractClause[]>([]);
  const [selectedClauseId, setSelectedClauseId] = useState<string>("");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isCompleting, setIsCompleting] = useState(false);

  useEffect(() => {
    let isMounted = true;

    async function loadContractAndFlags() {
      if (!contractId || !token) {
        setIsLoading(false);
        return;
      }

      try {
        setIsLoading(true);
        setError(null);

        const [contractDoc, flagsData] = await Promise.all([
          getContractById(contractId, token).catch(() => null),
          getContractFlags(contractId, token).catch(() => []),
        ]);

        if (isMounted) {
          if (contractDoc) {
            setContractTitle(contractDoc.title || "Contract Review");
            setContractType(
              contractDoc.contractType === "employment"
                ? "EMPLOYMENT AGREEMENT"
                : contractDoc.contractType.toUpperCase(),
            );
          }

          const transformed = flagsData.map((f, idx) =>
            transformFlagToClause(f, idx),
          );

          setClauses(transformed);
          if (transformed.length > 0) {
            setSelectedClauseId(transformed[0]?.id || "");
          }
        }
      } catch (err: unknown) {
        if (isMounted) {
          const msg =
            err instanceof Error
              ? err.message
              : "Failed to load contract review.";
          setError(msg);
        }
      } finally {
        if (isMounted) {
          setIsLoading(false);
        }
      }
    }

    loadContractAndFlags();

    return () => {
      isMounted = false;
    };
  }, [contractId, token]);

  const selectedClause = useMemo(
    () =>
      clauses.find((clause) => clause.id === selectedClauseId) ?? clauses[0],
    [clauses, selectedClauseId],
  );

  const highCount = clauses.filter((c) => c.riskLevel === "high").length;
  const mediumCount = clauses.filter((c) => c.riskLevel === "medium").length;
  const clearCount = clauses.filter((c) => c.riskLevel === "low").length;

  function handleClauseUpdated(updated: ContractClause) {
    setClauses((prev) => prev.map((c) => (c.id === updated.id ? updated : c)));
  }

  async function handleCompleteReview() {
    if (!contractId || !token) return;

    try {
      setIsCompleting(true);
      await completeContractReview(
        contractId,
        { attorneyNotes: "Reviewed and approved by counsel." },
        token,
      );
      navigate("/attorney");
    } catch (err: unknown) {
      const msg =
        err instanceof Error ? err.message : "Failed to complete review.";
      setError(msg);
    } finally {
      setIsCompleting(false);
    }
  }

  if (isLoading) {
    return (
      <div className="my-16 flex justify-center py-12">
        <span className="font-mono text-xs text-ink-soft animate-pulse">
          Loading AI clause analysis from database...
        </span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="my-8 rounded-[6px] border border-maroon/30 bg-maroon/5 p-4 text-xs font-mono text-maroon">
        {error}
      </div>
    );
  }

  return (
    <div className="flex flex-col">
      {/* Document Header */}
      <div className="mb-7">
        <span className="mb-2 block font-mono text-[11.5px] font-medium tracking-[0.06em] text-maroon uppercase">
          {contractType}
        </span>
        <div className="flex flex-wrap items-baseline justify-between gap-4">
          <h1 className="font-serif text-[28px] font-medium tracking-[-0.01em] text-navy-deep">
            {contractTitle} · {clauses.length} clauses analyzed
          </h1>
          <div className="flex flex-wrap items-center gap-4 text-[12.5px] text-ink-soft">
            <span className="flex items-center gap-1.5 font-mono text-xs">
              <span className="h-[7px] w-[7px] rounded-full bg-maroon" />
              {highCount} high-risk
            </span>
            <span className="flex items-center gap-1.5 font-mono text-xs">
              <span className="h-[7px] w-[7px] rounded-full bg-gold" />
              {mediumCount} medium
            </span>
            <span className="flex items-center gap-1.5 font-mono text-xs">
              <span className="h-[7px] w-[7px] rounded-full bg-green" />
              {clearCount} clear
            </span>

            <button
              type="button"
              onClick={handleCompleteReview}
              disabled={isCompleting}
              className="ml-2 rounded-[5px] bg-maroon px-4 py-2 text-xs font-semibold text-parchment hover:bg-maroon-bright disabled:opacity-60 cursor-pointer"
            >
              {isCompleting
                ? "Releasing Report…"
                : "Complete & Release Report →"}
            </button>
          </div>
        </div>
      </div>

      {clauses.length === 0 ? (
        <div className="rounded-[8px] border border-line bg-white p-10 text-center shadow-2xs">
          <p className="font-serif text-lg font-medium text-navy-deep">
            No text clauses were extracted for this file.
          </p>
          <p className="mt-1 text-sm text-ink-soft">
            This contract may have been uploaded as a blank or low-resolution
            image and is pending manual transcription.
          </p>
        </div>
      ) : (
        /* 2-Column Review Grid */
        <div className="grid grid-cols-1 items-start gap-[22px] md:grid-cols-[320px_1fr]">
          <ClauseList
            clauses={clauses}
            selectedClauseId={selectedClauseId}
            onSelectClause={setSelectedClauseId}
          />

          {selectedClause && (
            <ClauseDetailPanel
              key={selectedClause.id}
              clause={selectedClause}
              onClauseUpdated={handleClauseUpdated}
            />
          )}
        </div>
      )}
    </div>
  );
}

export default ReviewQueuePage;
