import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import ClauseList from "../../components/attorney/ClauseList.js";
import ClauseDetailPanel from "../../components/attorney/ClauseDetailPanel.js";
import { useAuth } from "../../context/AuthContext.js";
import { useToast } from "../../context/ToastContext.js";
import { getContractById } from "../../services/contractService.js";
import {
  completeContractReview,
  getContractFlags,
  type BackendFlag,
} from "../../services/attorneyService.js";
import type { ContractClause } from "../../types/clause.js";

function formatCategoryTitle(
  category: string | undefined,
  index: number,
  text: string,
): string {
  const titleMap: Record<string, string> = {
    wage_and_hours: "Wage & Working Hours",
    termination: "Termination & Due Process",
    non_compete: "Non-Compete Covenant",
    confidentiality: "Confidentiality Scope",
    liability_waiver: "Liability & Injury Waiver",
    intellectual_property: "IP Assignment",
    jurisdiction: "Jurisdiction & Venue",
    contracting_and_subcontracting: "Contracting Terms",
  };

  if (category && titleMap[category]) {
    return titleMap[category];
  }

  const firstLine = text.split("\n")[0]?.trim();
  if (firstLine && firstLine.length < 45 && !firstLine.includes('"')) {
    return firstLine;
  }

  return `Clause Section ${index + 1}`;
}

function transformFlagToClause(
  flag: BackendFlag,
  index: number,
): ContractClause {
  const primaryCategory = flag.riskCategories?.[0] || "other";
  const title = formatCategoryTitle(primaryCategory, index, flag.clauseText);

  const effectiveRisk = flag.attorneyRiskOverride || flag.aiRiskLevel || "low";
  const primaryStatute = flag.statutoryBases?.[0];

  const clause: ContractClause = {
    id: flag._id,
    clauseNumber: String(index + 1),
    title,
    riskLevel: effectiveRisk,
    originalAiRiskLevel: flag.aiRiskLevel || "low",
    attorneyStatus: flag.attorneyStatus || "pending",
    attorneyNote: flag.attorneyNote || "",
    quotedText: flag.clauseText,
  };

  if (flag.aiRationale) {
    clause.flagReason = flag.aiRationale;
  }

  if (primaryStatute) {
    clause.legalBasis = {
      citation: primaryStatute.citation,
      explanation: primaryStatute.excerpt,
    };
  }

  return clause;
}

/**
 * The live clause-by-clause AI-flagged review interface for attorneys.
 * Fetches real contract flags from MongoDB Atlas generated by the RAG pipeline.
 */
function ReviewQueuePage() {
  const navigate = useNavigate();
  const { contractId: paramContractId } = useParams<{ contractId: string }>();
  const [searchParams] = useSearchParams();
  const contractId = paramContractId || searchParams.get("id") || "";
  const { token } = useAuth();
  const { showToast } = useToast();

  const [contractTitle, setContractTitle] = useState("Contract Review");
  const [contractType, setContractType] = useState("Employment Agreement");
  const [clauses, setClauses] = useState<ContractClause[]>([]);
  const [selectedClauseId, setSelectedClauseId] = useState<string>("");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isCompleting, setIsCompleting] = useState(false);

  useEffect(() => {
    let isMounted = true;

    async function loadContractAndFlags() {
      if (!contractId || !token) {
        setIsLoading(false);
        return;
      }

      try {
        setIsLoading(true);
        setError(null);

        const [contractDoc, flagsData] = await Promise.all([
          getContractById(contractId, token).catch(() => null),
          getContractFlags(contractId, token).catch(() => []),
        ]);

        if (isMounted) {
          if (contractDoc) {
            setContractTitle(contractDoc.title || "Contract Review");
            setContractType(
              contractDoc.contractType === "employment"
                ? "EMPLOYMENT AGREEMENT"
                : contractDoc.contractType.toUpperCase(),
            );
          }

          const transformed = flagsData.map((f, idx) =>
            transformFlagToClause(f, idx),
          );

          setClauses(transformed);
          if (transformed.length > 0) {
            setSelectedClauseId(transformed[0]?.id || "");
          }
        }
      } catch (err: unknown) {
        if (isMounted) {
          const msg =
            err instanceof Error
              ? err.message
              : "Failed to load contract review.";
          setError(msg);
        }
      } finally {
        if (isMounted) {
          setIsLoading(false);
        }
      }
    }

    loadContractAndFlags();

    return () => {
      isMounted = false;
    };
  }, [contractId, token]);

  const selectedClause = useMemo(
    () =>
      clauses.find((clause) => clause.id === selectedClauseId) ?? clauses[0],
    [clauses, selectedClauseId],
  );

  const highCount = clauses.filter((c) => c.riskLevel === "high").length;
  const mediumCount = clauses.filter((c) => c.riskLevel === "medium").length;
  const clearCount = clauses.filter((c) => c.riskLevel === "low").length;

  const reviewedCount = clauses.filter(
    (c) => c.attorneyStatus === "approved" || c.attorneyStatus === "overridden",
  ).length;
  const progressPct =
    clauses.length > 0 ? Math.round((reviewedCount / clauses.length) * 100) : 0;

  const currentIndex = useMemo(() => {
    return clauses.findIndex((c) => c.id === selectedClauseId);
  }, [clauses, selectedClauseId]);

  function handleNextClause() {
    if (currentIndex >= 0 && currentIndex < clauses.length - 1) {
      const nextClause = clauses[currentIndex + 1];
      if (nextClause) {
        setSelectedClauseId(nextClause.id);
      }
    }
  }

  function handlePrevClause() {
    if (currentIndex > 0) {
      const prevClause = clauses[currentIndex - 1];
      if (prevClause) {
        setSelectedClauseId(prevClause.id);
      }
    }
  }

  function handleClauseUpdated(updated: ContractClause) {
    setClauses((prev) => prev.map((c) => (c.id === updated.id ? updated : c)));
  }

  async function handleCompleteReview() {
    if (!contractId || !token) return;

    try {
      setIsCompleting(true);
      await completeContractReview(
        contractId,
        { attorneyNotes: "Reviewed and approved by counsel." },
        token,
      );
      showToast("Contract review completed & released to client.", "success");
      navigate("/attorney");
    } catch (err: unknown) {
      const msg =
        err instanceof Error ? err.message : "Failed to complete review.";
      setError(msg);
      showToast("Failed to complete review", "warning");
    } finally {
      setIsCompleting(false);
    }
  }

  if (isLoading) {
    return (
      <div className="my-16 flex justify-center py-12 animate-fade-in-up">
        <span className="font-mono text-xs text-ink-soft animate-pulse">
          Loading AI clause analysis from database...
        </span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="my-8 rounded-xl border border-maroon/30 bg-maroon/5 p-4 text-xs font-mono text-maroon animate-fade-in-up">
        {error}
      </div>
    );
  }

  return (
    <div className="flex flex-col">
      {/* Sticky Document Header Toolbar */}
      <div className="sticky top-0 z-20 -mx-6 md:-mx-11 px-6 md:px-11 py-3.5 bg-parchment/95 backdrop-blur-md border-b border-line shadow-2xs mb-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 mb-0.5">
              <span className="font-mono text-[10.5px] font-semibold tracking-wider text-maroon uppercase">
                {contractType}
              </span>
              <span className="text-ink-soft/40">•</span>
              <span className="font-mono text-[10.5px] font-medium text-ink-soft flex items-center gap-1">
                <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                <span>
                  {reviewedCount} of {clauses.length} reviewed ({progressPct}%)
                </span>
              </span>
            </div>
            <h1 className="font-serif text-lg md:text-2xl font-medium tracking-tight text-navy-deep truncate">
              {contractTitle}
            </h1>
          </div>

          <div className="flex flex-wrap items-center gap-3 shrink-0">
            <div className="hidden sm:flex items-center gap-3 text-xs text-ink-soft bg-white/80 border border-line/80 px-3 py-1.5 rounded-xl shadow-2xs">
              <span className="flex items-center gap-1.5 font-mono text-[11px]">
                <span className="h-2 w-2 rounded-full bg-maroon" />
                {highCount} high
              </span>
              <span className="flex items-center gap-1.5 font-mono text-[11px]">
                <span className="h-2 w-2 rounded-full bg-gold" />
                {mediumCount} med
              </span>
              <span className="flex items-center gap-1.5 font-mono text-[11px]">
                <span className="h-2 w-2 rounded-full bg-green" />
                {clearCount} clear
              </span>
            </div>

            <button
              type="button"
              onClick={handleCompleteReview}
              disabled={isCompleting}
              className="flex items-center gap-2 rounded-xl bg-maroon px-4 py-2 text-xs font-semibold text-parchment hover:bg-maroon-bright transition-colors disabled:opacity-60 shadow-xs cursor-pointer"
            >
              <span>{isCompleting ? "Releasing Report…" : "Complete & Release Report"}</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>

      {clauses.length === 0 ? (
        <div className="rounded-2xl border border-line bg-white p-10 text-center shadow-xs">
          <p className="font-serif text-lg font-medium text-navy-deep">
            No text clauses were extracted for this file.
          </p>
          <p className="mt-1 text-sm text-ink-soft">
            This contract may have been uploaded as a blank or low-resolution
            image and is pending manual transcription.
          </p>
        </div>
      ) : (
        /* 2-Column Split-Pane Workbench */
        <div className="grid grid-cols-1 items-start gap-5 md:grid-cols-[330px_1fr]">
          <div className="md:sticky md:top-[85px]">
            <ClauseList
              clauses={clauses}
              selectedClauseId={selectedClauseId}
              onSelectClause={setSelectedClauseId}
            />
          </div>

          <div className="md:sticky md:top-[85px] max-h-[calc(100vh-140px)] overflow-y-auto pr-1">
            {selectedClause && (
              <ClauseDetailPanel
                key={selectedClause.id}
                clause={selectedClause}
                onClauseUpdated={handleClauseUpdated}
                currentIndex={currentIndex}
                totalClauses={clauses.length}
                hasPrevClause={currentIndex > 0}
                hasNextClause={currentIndex >= 0 && currentIndex < clauses.length - 1}
                onPrevClause={handlePrevClause}
                onNextClause={handleNextClause}
              />
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default ReviewQueuePage;
