import { useEffect, useRef } from "react";

interface TermsModalProps {
  open: boolean;
  onClose: () => void;
}

/**
 * Terms and Conditions modal for Lingkod Batas.
 *
 * NOTE: The clause text below is placeholder copy drafted to match the
 * product's stated behavior (AI-assisted review, attorney sign-off before
 * a report is finalized, no attorney-client relationship until then).
 * Replace with counsel-reviewed Terms and Conditions before shipping.
 */
function TermsModal({ open, onClose }: TermsModalProps) {
  const dialogRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;

    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") onClose();
    }

    document.addEventListener("keydown", handleKeyDown);
    dialogRef.current?.focus();

    const { overflow } = document.body.style;
    document.body.style.overflow = "hidden";

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.body.style.overflow = overflow;
    };
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-navy-deep/50 px-4 py-8"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="terms-modal-title"
        tabIndex={-1}
        className="flex max-h-[85vh] w-full max-w-[600px] flex-col overflow-hidden rounded-lg bg-white shadow-xl outline-none"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-line px-6 py-4.5">
          <h2
            id="terms-modal-title"
            className="font-serif text-lg font-medium text-navy-deep"
          >
            Terms and Conditions
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close terms and conditions"
            className="flex h-7 w-7 items-center justify-center rounded-full text-ink-soft hover:bg-parchment hover:text-ink cursor-pointer"
          >
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              className="h-4 w-4"
            >
              <path d="M18 6L6 18M6 6l12 12" strokeLinecap="round" />
            </svg>
          </button>
        </div>

        {/* Scrollable body */}
        <div className="overflow-y-auto px-6 py-5 text-[13.5px] leading-[1.6] text-ink">
          <p className="mb-4 font-mono text-[10.5px] tracking-[0.05em] text-ink-soft uppercase">
            Last updated: August 24, 2026
          </p>

          <Section title="1. Acceptance of Terms">
            By creating an account or uploading a document to Lingkod Batas, you
            agree to be bound by these Terms and Conditions. If you do not
            agree, please do not use the platform.
          </Section>

          <Section title="2. Description of Service">
            Lingkod Batas is an AI-assisted platform that reviews draft
            employment contracts for clauses that may raise concerns under
            Philippine labor law. The platform flags potentially unfair or
            non-compliant provisions and generates a preliminary summary for
            your reference.
          </Section>

          <Section title="3. No Attorney-Client Relationship Until Validation">
            Submitting a document for review is a request for preliminary,
            AI-assisted analysis only. It does not, by itself, create an
            attorney-client relationship. An attorney-client relationship is
            formed only when a reviewing attorney affirmatively accepts and
            validates your submission. Until that point, no attorney is
            representing you, and communications through the platform are not
            protected by attorney-client privilege.
          </Section>

          <Section title="4. Nature and Limits of AI-Generated Output">
            Risk flags, clause summaries, and answers to frequently asked
            questions generated by the platform's AI are informational aids
            only. They are grounded in general principles of Philippine labor
            law but are not a substitute for individualized legal advice. All
            AI-generated output is subject to review and approval by a licensed
            attorney before it is treated as final, and may be corrected,
            qualified, or withdrawn during that review.
          </Section>

          <Section title="5. No Legal Representation Implied">
            Nothing on this platform, including AI-generated output, constitutes
            legal representation, a legal opinion, or a guarantee of any
            outcome. Use of the platform does not obligate any attorney to
            represent you in a dispute, negotiation, or proceeding.
          </Section>

          <Section title="6. User Responsibilities">
            You agree to provide accurate information, to upload only documents
            you have the right to share, and to use the platform for personal,
            non-commercial contract review. You are responsible for decisions
            you make based on any report, with or without attorney validation.
          </Section>

          <Section title="7. Confidentiality and Data Handling">
            Documents you upload are handled in accordance with our Privacy
            Policy. Reasonable safeguards are used to protect your information;
            however, no online platform can guarantee absolute security.
          </Section>

          <Section title="8. Limitation of Liability">
            To the fullest extent permitted by law, Lingkod Batas and its
            attorneys are not liable for damages arising from reliance on
            AI-generated output that has not been validated by a reviewing
            attorney, or from any decision made prior to such validation.
          </Section>

          <Section title="9. Changes to These Terms">
            These Terms may be updated from time to time. Continued use of the
            platform after changes take effect constitutes acceptance of the
            revised Terms.
          </Section>

          <Section title="10. Governing Law">
            These Terms are governed by the laws of the Republic of the
            Philippines.
          </Section>
        </div>

        {/* Footer */}
        <div className="border-t border-line px-6 py-4">
          <button
            type="button"
            onClick={onClose}
            className="w-full rounded-[6px] bg-maroon p-3 text-[13.5px] font-semibold text-parchment transition-colors hover:bg-maroon-bright cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mb-5">
      <h3 className="mb-1.5 font-serif text-[14.5px] font-medium text-navy-deep">
        {title}
      </h3>
      <p className="text-ink-soft">{children}</p>
    </div>
  );
}

export default TermsModal;
