name: Send Push Notification to Discord

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "info" # Keeps the blue/info sidebar
          description: "A developer pushed updates to the repository."
          details: |
            👤 **Pushed By:** ${{ github.actor }}
            💬 **Message:** ${{ github.event.head_commit.message }}
            📦 **Repository:** `ZamSP31/lingkod-batas`
            🔗 **Commit Link:** ${{ github.event.head_commit.url }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
